events { }
http {
    include /etc/nginx/mime.types;
    types {
        application/wasm wasm;
        application/javascript js;
    }
    server {
        listen 80;
        index index.html;
        root /usr/share/nginx/html;
        location / {
            try_files $uri $uri/ /index.html;
        }
        location /_framework/ {
            try_files $uri =404;
        }
    }
}